apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zxcoe2f4s-java-quarkus-prod
  namespace: rhtap
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/zxcoe2f4s-java-quarkus/overlays/prod
    repoURL: https://github.com/rhtap-rhdh-qe/zxcoe2f4s-java-quarkus-gitops.git
    targetRevision: main
  destination:
    namespace: rhtap-app-prod
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: rhtap
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
